#!/bin/bash

#CLI for Termux Terminal.
termux() {
	echo "[+] Setting CLI and packages for Termux Terminal..."
	apt update && apt upgrade -y
	apt install -y tor wget openjdk-17
	apt install -y curl exiftool 
	chmod +x $HOME/CHALOTx/chalot
	mv $HOME/CHALOTx/chalot $PREFIX/bin
}
linux() {
	echo "[+] Setting CLI and packages for $NAME ..."
	sudo apt update && sudo apt full-upgrade -y
	sudo apt install -y torsocks default-jdk dnsenum nikto libimage-exiftool-perl
	sudo dpkg --configure -a
	sudo apt --fix-broken install
	sudo apt install -f
	sudo apt autoclean
	sudo apt autoremove
	chmod +x chalot
	sudo mv chalot /usr/local/bin
}
if [ "$PREFIX" = "/data/data/com.termux/files/usr" ]; then
	echo "Environment  : Termux Terminal"
	echo "Termux Type  : $TERM"
	echo "SHELL        : $SHELL"
	echo "HOME         : $HOME"
	echo "PREFIX       : $PREFIX"
	termux
elif [ -f /etc/os-release ]; then
	#Source /etc/os-release to check info.
	. /etc/os-release

	#Check name Os.
	if echo "$NAME" | grep -qi "kali"; then
		echo "Environment   : Kali Linux"
		echo "Terminal Type : $TERM"
		echo "SHELL         : $SHELL"
		linux
	elif echo "$NAME" | grep -qi "ubuntu"; then
		echo "Environment   : Ubuntu Linux"
		echo "Terminal Type : $TERM"
		echo "SHELL         : $SHELL"
		linux
	fi
fi
